# This workflow will run fairtally on the RSD data once an hour and push the results to the repo
#
# TODO:
#    - push result to repo
#    - generate an overview from the report and automatically create an issue out of that?
#    - set frequency to daily or weekly and move to TL repo?

name: Fairtally

on:  
  schedule:   
    - cron: "0 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fairtally:

    runs-on: ubuntu-latest

    env: 
       APIKEY_GITHUB: ${{ secrets.apikey }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      - name: Install fairfairtally
        run: pip3 install wheel howfairis fairtally
      - name: Run fairtally
        run: fairtally -o reports/report-`date +%Y%m%d-%H%M`.html https://github.com/xenon-middleware/xenon
