# This workflow will run fairtally on the RSD data once an hour and push the results to the repo
#
# TODO:
#    - push result to repo
#    - generate an overview from the report and automatically create an issue out of that?
#    - set frequency to daily or weekly and move to TL repo?

name: Fairtally

on:  
  schedule:   
    - cron: "0 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fairtally:

    runs-on: ubuntu-latest

    steps:
      - name: get a timestamp
        id: timestamp
        run: echo "::set-output name=date::$(date '+%Y%m%d-%H%M')"     
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      - name: Install fairfairtally
        run: pip3 install wheel howfairis fairtally

      - name: Get the data dump from the RSD
        run: curl https://research-software.nl/api/software > software.json

      - name: Extract the list of URLs 
        run: cat software.json | jq -r '[.[].repositoryURLs.github] | flatten | .[]' > urls.txt
        
      - name: Run fairtally
        run: fairtally -o reports/report-${{steps.timestamp.outputs.date}}.html -i urls.txt 
        env: 
           APIKEY_GITHUB: ${{ secrets.APIKEY_GITHUB }}

      - name: Commit report
        run: | 
           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
           git add reports
           git commit -m "Add generated report" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
